version: '3'

services:
  web:
    image: nginx
    container_name: webserver
    volumes:
      - ./cfg:/etc/nginx/
      - ./src:/var/www/localhost/htdocs
      - ./crt:/etc/ssl/certs
      - ./ssl:/etc/ssl/private

    depends_on:
      - db

    networks:
      default:
        ipv4_address: 192.168.20.2



  lb:
    container_name: my_lb
    image: jrofurtado/nghttpx-autoreload-with-healthcheck:1.0.0
    environment:
      PARAMS: '
        -f"*,443;" 
        -b"web,443;;dns;"
        -f"*,80;no-tls" 
        -b"web,8000;;dns;"
        -f"*,110;no-tls" 
        -b"roundcube,110;;dns;"
        -f"*,25;no-tls" 
        -b"roundcube,25;;dns;"
        -f"*,143;no-tls" 
        -b"roundcube,143;;dns;"
        -f"*,465;no-tls" 
        -b"roundcube,465;;dns;"
        -f"*,933;no-tls" 
        -b"roundcube,933;;dns;"
        -f"*,955;no-tls" 
        -b"roundcube,955;;dns;"
        -f"*,3306;no-tls"
        -b"db,3306;;dns;"'

    ports:
      - 8000:8000
      - 443:443
      - 25:25
      - 110:110
      - 143:143
      - 465:465
      - 933:933
      - 955:955
      - 3306:3306


    volumes:
      - lb-data:/volume
    networks:
      default:
        ipv4_address: 192.168.20.3
  
  roundcube:
    image: marooou/postfix-roundcube
    container_name: roundcube
    tty: true
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/vmail/:/var/vmail
      - ./data/log:/var/log
    environment:
      - "ADMIN_USERNAME=root"
      - "ADMIN_PASSWD=Passw0rd" 
      - "DOMAIN_NAME=mail.local"
    ports:
      - 80:80

    networks:
      default:
        ipv4_address: 192.168.20.4

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000

    networks:
      default:
        ipv4_address: 192.168.20.5


  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'Passw0rd'
      MYSQL_ROOT_PASSWORD: 'Passw0rd'

    volumes:
      - ./conf-db:/var/lib/mysql
    networks:
      default:
        ipv4_address: 192.168.20.6



volumes:
  lb-data:
    external: false

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24